### ISSUE TITLE
Add a server example to README.md

### ISSUE THREAD

**Issue by brianquinlan** [google/pybadges#1]
e.g. an example continuous integration server that serves this badge

**Comment by khalithartmann** [comment]
that post might help : https://jira.atlassian.com/browse/BCLOUD-13522?error=consent_required&error_description=Consent+required&state=70a8db2f-71a9-45d0-bca6-9d58cad5adaf

**Comment by AlexeyDer** [comment]
https://github.com/google/pybadges/tree/master/server-example
