### ISSUE TITLE
Upgrade to Flask 2.0?

### ISSUE THREAD

**Issue by aegaas** [google/pybadges#31]
This project has a dependency on jinja2, which is preventing our service from updating to Flask 2.0.

We'd love to continue using pybadges, but may need to replace it in order to upgrade if a new maintainer does not come forward.

**Comment by brianquinlan** [comment]
I think that this is fixed in https://github.com/google/pybadges/pull/33 (which is in the pybadges 3.0.0 release)

**Comment by brianquinlan** [comment]
Please reopen if that is not the case.
