### ISSUE TITLE
colorscheme.json superceded by color.js

### ISSUE THREAD

**Issue by epogrebnyak** [google/pybadges#35]
https://github.com/google/pybadges/blob/5973dbf35dc32d394166a6d4db7693ecb65a8452/pybadges/__init__.py#L53

Colors are noew listed at <https://github.com/badges/shields/blob/master/badge-maker/lib/color.js>

**Comment by epogrebnyak** [comment]
Same update needed here: https://github.com/google/pybadges/blob/1f4de8796e7e0c19723054bccd41c6665e10e0a2/pybadges/__init__.py#L152-L161

**Comment by brianquinlan** [comment]
Fixed in 3.0.1
