### ISSUE TITLE
Python 2.7

### ISSUE THREAD

**Issue by u1i** [google/pybadges#4]
Works great with Python 3.6, no luck with 2.7 though. Fails with an ugly error message:

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/usr/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "/home/uli/projects/badges1/local/lib/python2.7/site-packages/pybadges/__init__.py", line 74
    def badge(left_text: str, right_text: str, left_link: Optional[str] = None,
                       ^
SyntaxError: invalid syntax

**Comment by aritra24** [comment]
I think that might be because of the use of function annotations which was introduced in python 3. Removing all instances of annotations and replacing them with informative comments should fix the issue. I'm not very well versed in python yet so I might not be completely right. I can work on this.

**Comment by brianquinlan** [comment]
Hey @u1i,

This project is not compatible with Python 2.7 and making it so would mean removing all of the type annotations, which I'd prefer not to do.

Is there some reason why you are stuck on Python 2.7?

Cheers,
Brian

**Comment by u1i** [comment]
yes I was looking at the code, and realized it's not compatible with 2.7.
Let's add a version check at the beginning just in case, so there's a 'nice' error message instead the stack trace.

I'll have to do more 3.x but not all environments allow you to choose the version.

**Comment by brianquinlan** [comment]
It would be difficult to do a version check at the beginning of the code because the code isn't even run because it is not valid Python 2.7 code...

It looks like the bug is that pybadges is pip installable in Python 2. I'll fix that.
