### ISSUE TITLE
Logo Disappears

### ISSUE THREAD

**Issue by shadowrylander** [google/pybadges#7]
Hello!
I am trying to use the python logo:

![](https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg)

in one of the badges; even when downloading it and using it in the command, I cannot seem to get it to display anywhere except when it is situated on my computer and shown in my browser.
The code I am using to create it:
```bash
/home/shadowrylander/miniconda3/envs/pypy3/bin/pypy3 -m pybadges \
    --left-text=t1 \
    --right-text=t2 \
    --left-color=yellow \
    --right-color=blue \
    --logo="https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg" \
    --browser
```
This is how I'm seeing it:
https://www.dropbox.com/s/wixt0mpx9ne93id/pypy3.svg?dl=0
So similar to the python example in the `README.md` with the regular url.
Thank you kindly for the help!

**Comment by brianquinlan** [comment]
Interesting, when I save that file and view it locally, I see the image. I assumed that the problem with README.md was related to how github proxies. Let me check...

**Comment by brianquinlan** [comment]
Interesting, when you look at the dropbox URL directly:
https://uc3fcebf00b83f692358e41a69b9.previews.dropboxusercontent.com/p/orig/AAWVnIG65585EBDS5YH-KZlF5k9pKv65aB4kDNO69rCSjaKeC8wsr39JZT2HQAhPC_b4--6Scl-BNJgbwIPthq037XE8hYxNHVFKCkUC18yRoaNC5nUuLzK-XmLUhN_LizmW3ULx4qVv9XUanaa0kiyvb2wRgAFrOxIM3yYT3pLmja5HRSBofAe9scZ22q0pSbLdQC7qGwaivnqqTbp684wtX68fMsrQiudiRQDZnePNeWKLdCIh1IiU-CN2VM34h11iP3ltms6vKiW-7IWBMVW0OOl3kDNuW0Pf_JypWQVWNhon5u_fo504vSPIpJV7RpOnpwSBmeMkJVkta7iADPL8/p.svg?size_mode=5

it renders correctly.

**Comment by shadowrylander** [comment]
When I view it on the Dropbox mobile site, I still can't see the logo; in addition, it seems as though the link you posted won't let me in.

**Comment by brianquinlan** [comment]
So you see a broken link when you follow the link that I posted?

**Comment by brianquinlan** [comment]
Maybe it would be easier for pybadges to just embed logos into the generated SVG by default. @shadowrylander , would that work for your use case?

**Comment by shadowrylander** [comment]
Yes, it is apparently broken; also, it indeed would be easier to simply embed it, which would also allow me to see it on devices which have no internet, but have the files locally. Thank you!

**Comment by shadowrylander** [comment]
Thank you very much!

**Comment by brianquinlan** [comment]
No worries. Let me know if this doesn't solve your issues or you need help using it. I updated the README to include usage information.

**Comment by shadowrylander** [comment]
Of course! Also, has the update been pushed to the PyPi repos yet?

**Comment by shadowrylander** [comment]
Never mind; both questions answered! Thank you once again!
